config/routes.rb
Rails.application.routes.draw do

  get 'venues' => 'venues#index'
  get 'venues/new' => 'venues#new' , as: :new_venue
  post 'venues' => 'venues#create'

  root 'venues#index'

end

app/models/location_service.rb
require 'what3words'
class LocationService 
	
	def initialize
         @what3words = ::What3Words::API.new(:key => "KYNY25Q2")
    end

    def lookup_coords(lat,lon)

    	@what3words.position_to_words [lat,lon]

    end

    def lookup_words(words)

    	@what3words.words_to_position words
        
    end

end 

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
	layout 'application'	
	def index

		@venues = Venue.all
# example:

	end

	def new

	end

	def create
		venue = Venue.new
		venue.name = params[:name]
		venue.description = params[:description]
		venue.lat = params[:lat]
		venue.lon = params[:lon]
		words = LocationService.new.lookup_coords(venue.lat, venue.lon)
		venue.words = words.join('.')
		venue.save
		redirect_to('/venues')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlacesApp</title>

  <script src="http://maps.googleapis.com/maps/api/js"></script>
	<script>
	function initialize() {
	  var mapProp = {
	    center:new google.maps.LatLng(51.508742,-0.120850),
	    zoom:5,
	    mapTypeId:google.maps.MapTypeId.ROADMAP
	  };
	  var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
	}
	google.maps.event.addDomListener(window, 'load', initialize);
	</script>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/venues.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places App</title>
</head>
<div id="header">
	<h1>Places Application</h1>
</div>
<div id="main">
	<h1>Places Application</h1>
</div>
<body>

<%= yield %>

</body>
</html>

app/views/venues/_form.html.erb
<%= form_tag("/venues") do %>
  <p><%= label_tag(:name, "Enter Name:") %>
  <%= text_field_tag(:name) %></p>

  <p><%= label_tag(:description, "Enter Description:") %>
  <%= text_field_tag(:description) %></p>

  <p><%= label_tag(:lat, "Enter Latitude:") %>
  <%= text_field_tag(:lat) %></p>

  <p><%= label_tag(:lon, "Enter Longitude:") %>
  <%= text_field_tag(:lon) %></p>

  <%= submit_tag("Submit") %>
<% end %>

app/views/venues/index.html.erb
<h1 class="">Add Venue</h1>
<%= render partial: 'form', locals: { venue: @venue } %>
<h1>Venues List</h1>
<%= link_to 'Create New Venue', new_venue_path %>
<% @venues.each do |venue| %>
	<h1><%=venue.name %></h1>
	<p><%=venue.description %></p>
	<ul>
		<li><%=venue.lat %></li>
		<li><%=venue.lon %></li>
		<li><%=venue.words %></li>
	</ul>
<% end %>

app/views/venues/new.html.erb
<h2>Add a Venue</h2>
<%= render partial: 'form', locals: { venue: @venue } %>

<% params %>